# Generated by Django 5.0.3 on 2024-08-01 19:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('resume', models.FileField(upload_to='candidate_submissions/')),
                ('location', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_location', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_openings', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=10)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=6)),
                ('recruiter', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.FileField(blank=True, null=True, upload_to='job_descriptions/')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notice_period', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('position_status', models.CharField(blank=True, max_length=100, null=True)),
                ('interview_status', models.CharField(blank=True, max_length=100, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('sourcer', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('current_company', models.CharField(blank=True, max_length=100, null=True)),
                ('current_position', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years_months', models.CharField(blank=True, max_length=100, null=True)),
                ('relevant_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('current_salary_lpa', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_salary_lpa', models.CharField(blank=True, max_length=100, null=True)),
                ('other_offers_lpa', models.CharField(blank=True, max_length=100, null=True)),
                ('last_working_day', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_screening', models.DateField(blank=True, null=True)),
                ('date_of_interview_2', models.DateField(blank=True, null=True)),
                ('date_of_interview_3', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('evaluation_link', models.URLField(blank=True, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.interviewer')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.jobtitle')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.location')),
            ],
        ),
        migrations.CreateModel(
            name='SubStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_stages', to='candidates.stage')),
            ],
        ),
    ]
